--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: persona; Type: TABLE; Schema: public; Owner: fpiemontesi
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    nombre text NOT NULL,
    apellido text,
    "tipoDocumentoId" bigint NOT NULL
);


ALTER TABLE public.persona OWNER TO fpiemontesi;

--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: fpiemontesi
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipoDocumento; Type: TABLE; Schema: public; Owner: fpiemontesi
--

CREATE TABLE public."tipoDocumento" (
    id bigint NOT NULL,
    nombre text NOT NULL
);


ALTER TABLE public."tipoDocumento" OWNER TO fpiemontesi;

--
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: fpiemontesi
--

COPY public.persona (id, nombre, apellido, "tipoDocumentoId") FROM stdin;
2	roberto	carlos	2
3	Pablo	Farias	1
1	Jorge	Furtado	2
4	qw	qwe	1
5	qwe	wewww	2
6	a	b	1
7	c	d	2
\.


--
-- Data for Name: tipoDocumento; Type: TABLE DATA; Schema: public; Owner: fpiemontesi
--

COPY public."tipoDocumento" (id, nombre) FROM stdin;
1	DNI
2	Pasaporte
\.


--
-- Name: persona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fpiemontesi
--

SELECT pg_catalog.setval('public.persona_id_seq', 7, true);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: fpiemontesi
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: tipoDocumento tipoDocumento_pkey; Type: CONSTRAINT; Schema: public; Owner: fpiemontesi
--

ALTER TABLE ONLY public."tipoDocumento"
    ADD CONSTRAINT "tipoDocumento_pkey" PRIMARY KEY (id);


--
-- Name: persona fk_persona_tipoDocumento; Type: FK CONSTRAINT; Schema: public; Owner: fpiemontesi
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT "fk_persona_tipoDocumento" FOREIGN KEY ("tipoDocumentoId") REFERENCES public."tipoDocumento"(id);


--
-- PostgreSQL database dump complete
--

